'use strict';
module.exports = function() {
    var composer = {};
    composer.global = {
        'php': '>=5.5.9',
        'appventus/ajax-bundle': '^1.1',
        'appventus/alertify-bundle': '^1.0',
        'appventus/assetic-injector-bundle': '^1.0',
        'appventus/auto-form-fill-bundle': 'dev-master',
        'appventus/aviary-bundle': 'dev-master',
        'appventus/ossus-bundle': 'dev-master',
        'appventus/shortcuts-bundle': 'dev-master',
        'appventus/spoolmailerbundle': 'dev-master',
        'appventus/swiftmailerdbbundle': 'dev-master',
        'beberlei/doctrineextensions': '1.0.x-dev',
        'behat/mink': '1.7.x-dev',
        'doctrine/doctrine-bundle': '~1.4',
        'doctrine/data-fixtures': '1.1.x-dev',
        'doctrine/doctrine-fixtures-bundle': '2.2.x-dev',
        'doctrine/orm': 'v2.5.2',
        'ekino/newrelic-bundle': '^1.3@dev',
        'friendsofsymfony/jsrouting-bundle': '2.0.*@dev',
        'friendsofsymfony/user-bundle': '~2.0@dev',
        'friendsofvictoire/text-widget': '~1.5',
        'friendsofvictoire/button-widget': '~1.5',
        'imagine/imagine': 'v0.5.0',
        'incenteev/composer-parameter-handler': '~2.0',
        'infinite-networks/form-bundle': 'dev-master',
        'jms/di-extra-bundle': '~1.7',
        'jms/serializer-bundle': '^1.0',
        'jms/security-extra-bundle': '1.5.*@dev',
        'jms/translation-bundle': '1.1.*@dev',
        'knplabs/gaufrette': 'v0.1.7',
        'knplabs/knp-components': '1.3.*@dev',
        'knplabs/knp-menu': '2.1.*@dev',
        'knplabs/knp-menu-bundle': '2.1.*@dev',
        'lexik/form-filter-bundle': '3.*@dev',
        'liip/imagine-bundle': '1.0.*@dev',
        'mopa/bootstrap-bundle': '3.x-dev',
        'nelmio/alice': '2.*@dev',
        'pagerfanta/pagerfanta': '1.0.*@dev',
        'predis/predis': '^1.1@dev',
        'sensio/distribution-bundle': '>=2.3.x-dev',
        'sensio/framework-extra-bundle': '~3.0',
        'sensio/generator-bundle': '~2.3',
        'snc/redis-bundle': '2.x-dev',
        'stof/doctrine-extensions-bundle': '1.2.*@dev',
        'symfony/assetic-bundle': '~2.3',
        'symfony/monolog-bundle': '~2.4',
        'symfony/symfony': '~2.8|~3.0',
        'symfony/swiftmailer-bundle': '~2.3',
        'twig/extensions': '~1.0',
        'twig/twig': '~1.0',
        'twbs/bootstrap': '3.3.x-dev',
        'vlabs/media-bundle': 'dev-master',
        'willdurand/js-translation-bundle': '^2.5',
        'white-october/pagerfanta-bundle': '1.0.*@dev'
    };
    composer.dev = {
        'sensio/generator-bundle': '~2.3',
        'behat/behat': '~3.0',
        'behat/mink-browserkit-driver': '*',
        'behat/mink-extension': '~2.0',
        'behat/mink-goutte-driver': '~1.1',
        'behat/mink-selenium2-driver': '~1.1',
        'behat/symfony2-extension': '~2.0',
        'knplabs/friendly-contexts': 'dev-master',
        'symfony/var-dumper': '~2.8',
        'pugx/generator-bundle': '2.4.*',
        'emuse/behat-html-formatter': '^0.1.0',
        'jarnaiz/behat-junit-formatter': 'v1.3.1',
        'phpunit/phpunit': '^4.8',
        'phpspec/prophecy': '~1.0'
    };
    composer.victoire = {
        'victoire/victoire': '1.5.x-dev'
    };

    return composer;
};
